# =============================================================================
# File: R/SurrogateModeler.R
# Description: Surrogate model / virtual experiment generator
# Theory: Response surface approximation, Gaussian process, Monte Carlo noise,
#         digital twin
# Use cases: Pre-experiment validation, algorithm testing, digital twinning,
#            sample size estimation, teaching / training
# References: See docs/doe/ for the four references on surrogate models and
#            virtual experimentation.
# =============================================================================

#' @title SurrogateModeler: Surrogate Model and Virtual Experiment Generator
#' @description
#' An R6 class that implements three families of low-cost simulated
#' experimental data generation:
#'
#' 1. **Parameterised response surface**: a mathematical model derived from
#'    expert knowledge or the literature, combined with Monte Carlo noise.
#' 2. **Gaussian process surrogate**: a GP model trained on historical data
#'    that predicts the response (and its uncertainty) at new parameter
#'    settings.
#' 3. **Digital twin virtual DOE**: a complete DOE workflow executed in a
#'    virtual environment as a substitute for physical experimentation.
#'
#' **Theoretical background**:
#' - Santner, T. J., Williams, B. J., & Notz, W. I. (2018).
#'   *The Design and Analysis of Computer Experiments*.
#' - The four DOE frontier references on surrogate modelling, digital
#'   twinning and virtual experimentation provided by the user.
#'
#' @export
SurrogateModeler <- R6::R6Class("SurrogateModeler",
  public = list(

    #' @description Create a new SurrogateModeler instance.
    #' @return A `SurrogateModeler` instance (invisibly).
    initialize = function() {
      invisible(self)
    },

    # =========================================================================
    # Method 1: Parameterised response surface + noise simulation
    # =========================================================================

    #' @description Generate simulated experimental data from a parameterised
    #'   response surface. The supplied `response_model` is evaluated on the
    #'   design to obtain the noise-free ("true") response, to which Gaussian
    #'   measurement noise and (optionally) batch effects are added. The input
    #'   `design` data frame is never mutated; a copy is returned with the
    #'   additional result columns appended.
    #' @param design Data frame of experimental settings (e.g. a CCD, LHS or
    #'   orthogonal array) generated by an upstream DOE planner.
    #' @param response_model Function that takes a data frame and returns a
    #'   numeric vector of noise-free responses.
    #' @param noise_sd Numeric. Standard deviation of the Gaussian measurement
    #'   noise (defaults to `0`, i.e. no noise).
    #' @param batch_effect Logical. If `TRUE`, add a random batch effect to
    #'   each run.
    #' @param n_batches Integer. Number of batches (used only when
    #'   `batch_effect = TRUE`).
    #' @param batch_sd Numeric. Between-batch standard deviation (used only
    #'   when `batch_effect = TRUE`).
    #' @param seed Random seed. When `NULL` the RNG state is left untouched.
    #' @return A copy of `design` with the additional columns
    #'   `Response_Observed` (noisy response), `Response_True` (noise-free
    #'   response) and, when `batch_effect = TRUE`, `Batch` (batch index).
    simulate_parameterized = function(design, response_model,
                                      noise_sd = 0, batch_effect = FALSE,
                                      n_batches = 3, batch_sd = 0, seed = NULL) {
      # Locally set and automatically restore the RNG state. withr::local_seed()
      # is a no-op when seed is NULL, so the explicit NULL guard is dropped.
      withr::local_seed(seed)

      # Do not mutate the caller's data frame: work on a local copy.
      design <- as.data.frame(design)

      n <- nrow(design)

      # Noise-free ("true") response from the supplied model
      y_true <- response_model(design)

      # Add Gaussian measurement noise
      y_obs <- y_true + rnorm(n, 0, noise_sd)

      # Add batch effects if requested
      if (batch_effect) {
        batch <- rep(1:n_batches, length.out = n)
        batch_effects <- rnorm(n_batches, 0, batch_sd)
        y_obs <- y_obs + batch_effects[batch]
        design$Batch <- batch
      }

      # Append result columns to the local copy
      design$Response_Observed <- y_obs
      design$Response_True <- y_true

      design
    },

    # =========================================================================
    # Method 2: Gaussian process surrogate trained on historical data
    # =========================================================================

    #' @description Train a Gaussian process surrogate model on historical
    #'   data. All columns of `historical_data` other than `response_col` are
    #'   treated as factors. Leave-one-out (LOO) predictions are computed to
    #'   estimate the model's predictive error.
    #' @param historical_data Data frame containing both the factor columns
    #'   and the response column.
    #' @param response_col Character. Name of the response column.
    #' @param kernel_type Character. Covariance kernel: `"rbf"` (default) for
    #'   the radial basis function kernel or `"matern"` for the Matern kernel.
    #' @return A list with elements `model` (the fitted `gausspr` object),
    #'   `factor_columns` (names of the factor columns), `n_training`
    #'   (number of training rows), `loo_rmse` (leave-one-out RMSE) and
    #'   `kernel_type` (the kernel that was used).
    train_surrogate_gp = function(historical_data, response_col,
                                  kernel_type = "rbf") {
      # Ensure kernlab is available before attempting to fit
      has_kernlab <- requireNamespace("kernlab", quietly = TRUE)
      if (!has_kernlab) {
        stop("[SM] kernlab is not installed. Run install.packages('kernlab').")
      }

      factor_cols <- setdiff(names(historical_data), response_col)
      X <- historical_data[, factor_cols, drop = FALSE]
      y <- historical_data[[response_col]]

      # Select the covariance kernel
      kern <- if (kernel_type == "rbf") {
        kernlab::rbfdot()
      } else if (kernel_type == "matern") {
        kernlab::materndot()
      } else {
        stop("[SM] Unsupported kernel_type '", kernel_type,
             "'. Choose 'rbf' or 'matern'.")
      }

      # Fit the Gaussian process
      gp_model <- kernlab::gausspr(x = X, y = y, kernel = kern, scaled = TRUE)

      # Leave-one-out residual estimation (model quality diagnostic)
      loo_pred <- numeric(length(y))
      for (i in seq_along(y)) {
        train_idx <- setdiff(seq_along(y), i)
        if (length(train_idx) >= 3) {
          sub_model <- kernlab::gausspr(
            x = X[train_idx, , drop = FALSE],
            y = y[train_idx],
            kernel = kern, scaled = TRUE
          )
          loo_pred[i] <- kernlab::predict(sub_model, X[i, , drop = FALSE])
        }
      }
      loo_rmse <- sqrt(mean((y - loo_pred)^2, na.rm = TRUE))

      list(
        model = gp_model,
        factor_columns = factor_cols,
        n_training = length(y),
        loo_rmse = loo_rmse,
        kernel_type = kernel_type
      )
    },

    #' @description Predict the response at new design points using a
    #'   previously trained GP surrogate. The prediction uncertainty is
    #'   approximated from the LOO RMSE stored on `gp_result`; optional
    #'   Gaussian noise can be added on top of the GP mean.
    #' @param gp_result Return value of `train_surrogate_gp()`.
    #' @param new_design Data frame of new design points. Must contain the
    #'   factor columns referenced by `gp_result`.
    #' @param add_noise Logical. If `TRUE`, add Gaussian noise of standard
    #'   deviation `noise_sd` to the GP mean.
    #' @param noise_sd Numeric. Standard deviation of the added noise. When
    #'   `NULL` (default), the LOO RMSE of `gp_result` is used.
    #' @param seed Random seed. When `NULL` the RNG state is left untouched.
    #' @return A list with elements `predict` (numeric vector of predicted
    #'   responses), `se` (standard error), `lower` and `upper` (lower and
    #'   upper bounds of an approximate 95% prediction interval).
    predict_with_gp = function(gp_result, new_design,
                               add_noise = FALSE, noise_sd = NULL, seed = NULL) {
      # Locally set and automatically restore the RNG state.
      withr::local_seed(seed)

      factor_cols <- gp_result$factor_columns
      X_new <- new_design[, factor_cols, drop = FALSE]

      # GP mean prediction
      mu <- kernlab::predict(gp_result$model, X_new)

      # Approximate predictive uncertainty from the LOO RMSE
      if (is.null(noise_sd)) {
        noise_sd <- gp_result$loo_rmse
      }

      # Optionally add noise on top of the GP mean
      if (add_noise) {
        y_sim <- as.numeric(mu) + rnorm(nrow(X_new), 0, noise_sd)
      } else {
        y_sim <- as.numeric(mu)
      }

      list(
        predict = y_sim,
        se = rep(noise_sd, length(y_sim)),
        lower = y_sim - 1.96 * noise_sd,
        upper = y_sim + 1.96 * noise_sd
      )
    },

    # =========================================================================
    # Method 3: Digital twin virtual DOE (full workflow simulation)
    # =========================================================================

    #' @description Run a complete DOE workflow in a virtual environment.
    #'   The experimental design is generated internally, the supplied
    #'   `true_response_fn` plays the role of the digital twin, and Gaussian
    #'   measurement noise (and optionally batch effects) are added to its
    #'   output.
    #' @param n_factors Integer. Number of factors in the design.
    #' @param factor_ranges List. Each element is a list with `name`,
    #'   `lower` and `upper` describing one factor.
    #' @param true_response_fn Function. The digital-twin response function;
    #'   takes a design data frame and returns a numeric vector of responses.
    #' @param doe_method Character. DOE method: `"ccd"` (central composite),
    #'   `"lhs"` (Latin hypercube, default) or `"full"` (full factorial at
    #'   two levels).
    #' @param n_runs Integer. Number of runs (used by `"lhs"`). When `NULL`,
    #'   defaults to `max(10 * n_factors, 20)`.
    #' @param n_center Integer. Number of center points (used by `"ccd"`).
    #' @param noise_sd Numeric. Standard deviation of the measurement noise.
    #' @param batch_effect Logical. If `TRUE`, add a batch effect.
    #' @param seed Random seed. When `NULL` the RNG state is left untouched.
    #' @return A list with elements `design` (the generated design with
    #'   appended `Response_Observed`, `Response_True` and `RunOrder`
    #'   columns, plus `Batch` when `batch_effect = TRUE`), `n_runs`,
    #'   `n_factors`, `doe_method`, `noise_sd` and `has_batch_effect`.
    virtual_doe_experiment = function(n_factors, factor_ranges,
                                       true_response_fn,
                                       doe_method = "lhs",
                                       n_runs = NULL,
                                       n_center = 0,
                                       noise_sd = 0,
                                       batch_effect = FALSE,
                                       seed = NULL) {
      # Locally set and automatically restore the RNG state.
      withr::local_seed(seed)

      # Default number of runs for LHS
      if (is.null(n_runs)) {
        n_runs <- max(10 * n_factors, 20)
      }

      design <- private$.generate_virtual_design(
        n_factors, factor_ranges, doe_method, n_runs, n_center
      )

      # Evaluate the digital twin to obtain the true response
      y_true <- true_response_fn(design)

      # Add measurement noise
      y_obs <- y_true + rnorm(nrow(design), 0, noise_sd)

      # Add batch effects if requested
      if (batch_effect) {
        n_batches <- 3
        batch <- rep(1:n_batches, length.out = nrow(design))
        batch_effects <- rnorm(n_batches, 0, noise_sd * 0.5)
        y_obs <- y_obs + batch_effects[batch]
        design$Batch <- batch
      }

      design$Response_Observed <- y_obs
      design$Response_True <- y_true
      design$RunOrder <- seq_len(nrow(design))

      list(
        design = design,
        n_runs = nrow(design),
        n_factors = n_factors,
        doe_method = doe_method,
        noise_sd = noise_sd,
        has_batch_effect = batch_effect
      )
    },

    # =========================================================================
    # Method 4: Built-in response models (quick start)
    # =========================================================================

    #' @description Retrieve a pre-defined response model for quick testing
    #'   or teaching. These built-in models are single-response models: each
    #'   returns a single primary response as a numeric vector (not a list),
    #'   so they can be plugged directly into `simulate_parameterized()` or
    #'   `virtual_doe_experiment()`. For multi-response problems, supply
    #'   your own response function.
    #' @param model_name Character. Name of the built-in model: `"welding"`
    #'   (returns weld strength in MPa), `"injection"` (returns injection
    #'   moulding tensile strength in MPa) or `"battery"` (returns battery
    #'   capacity retention in %).
    #' @return A function that takes a design data frame and returns a
    #'   numeric vector (the primary response of the selected model).
    get_builtin_model = function(model_name) {
      switch(model_name,
        "welding" = private$.model_welding,
        "injection" = private$.model_injection,
        "battery" = private$.model_battery,
        stop("[SM] Unknown model. Choose: welding, injection, or battery.")
      )
    }
  ),

  private = list(

    # -----------------------------------------------------------------------
    # Virtual design generation
    # -----------------------------------------------------------------------
    .generate_virtual_design = function(n_factors, factor_ranges, method, n_runs, n_center) {
      design <- data.frame()

      if (method == "lhs") {
        # Latin hypercube design.
        # Note: This is a simplified LHS approximation. Computing quantiles on
        # a two-element vector c(lower, upper) collapses to linear
        # interpolation between the bounds, and no per-dimension permutation
        # of the strata is applied, so the resulting samples are correlated
        # across factors. For a production-grade LHS, use a dedicated package
        # such as 'lhs'.
        for (i in seq_along(factor_ranges)) {
          fr <- factor_ranges[[i]]
          breaks <- quantile(c(fr$lower, fr$upper), probs = seq(0, 1, length.out = n_runs + 1))
          design[[fr$name]] <- runif(n_runs, min = breaks[-(n_runs + 1)], max = breaks[-1])
        }
      } else if (method == "full") {
        # Full factorial at two levels (lower / upper)
        levels_list <- lapply(factor_ranges, function(fr) c(fr$lower, fr$upper))
        names(levels_list) <- sapply(factor_ranges, function(fr) fr$name)
        design <- expand.grid(levels_list, stringsAsFactors = FALSE)
      } else if (method == "ccd") {
        # Simplified CCD: factorial + axial + center points
        # Factorial portion
        levels_list <- lapply(factor_ranges, function(fr) c(fr$lower, fr$upper))
        names(levels_list) <- sapply(factor_ranges, function(fr) fr$name)
        factorial_part <- expand.grid(levels_list, stringsAsFactors = FALSE)

        # Axial points. For a rotatable CCD, alpha = (2^k)^(1/4), where k is
        # the number of factors.
        alpha <- (2^n_factors)^(1 / 4)
        axial_points <- list()
        for (i in seq_len(n_factors)) {
          for (sign in c(-1, 1)) {
            point <- lapply(factor_ranges, function(fr) mean(c(fr$lower, fr$upper)))
            range_i <- factor_ranges[[i]]$upper - factor_ranges[[i]]$lower
            point[[i]] <- mean(c(factor_ranges[[i]]$lower, factor_ranges[[i]]$upper)) +
                          sign * alpha * range_i / 2
            axial_points[[length(axial_points) + 1]] <- as.data.frame(point)
          }
        }
        axial_part <- do.call(rbind, axial_points)

        # Center points
        center_values <- lapply(factor_ranges, function(fr) mean(c(fr$lower, fr$upper)))
        center_part <- as.data.frame(replicate(n_center, center_values, simplify = FALSE))
        names(center_part) <- sapply(factor_ranges, function(fr) fr$name)

        design <- rbind(factorial_part, axial_part, center_part)
      }

      design
    },

    # -----------------------------------------------------------------------
    # Built-in model: welding process
    # Single-response model: returns weld strength (MPa) as a numeric vector.
    # Inputs (columns 1-3): current (A), voltage (V), speed (mm/s).
    # -----------------------------------------------------------------------
    .model_welding = function(df) {
      current <- df[[1]]; voltage <- df[[2]]; speed <- df[[3]]

      # Weld strength (larger-the-better; has an optimum)
      strength <- 400 - 0.01 * (current - 180)^2 - 0.5 * (voltage - 25)^2 -
                  0.3 * (speed - 5)^2 + 0.1 * (current - 180) * (voltage - 25)

      strength
    },

    # -----------------------------------------------------------------------
    # Built-in model: injection moulding process
    # Single-response model: returns tensile strength (MPa) as a numeric vector.
    # Inputs (columns 1-3): temperature (deg. C), pressure (MPa), time (s).
    # -----------------------------------------------------------------------
    .model_injection = function(df) {
      temp <- df[[1]]; pressure <- df[[2]]; time <- df[[3]]

      # Tensile strength (larger-the-better)
      strength <- 50 + 0.2 * (temp - 240) - 0.001 * (temp - 240)^2 +
                  0.5 * (pressure - 50) - 0.002 * (pressure - 50)^2 +
                  0.01 * (temp - 240) * (pressure - 50)

      strength
    },

    # -----------------------------------------------------------------------
    # Built-in model: battery degradation
    # Single-response model: returns capacity retention (%) as a numeric vector.
    # Inputs (columns 1-3): charge rate (C), temperature (deg. C), cycles.
    # -----------------------------------------------------------------------
    .model_battery = function(df) {
      crate <- df[[1]]; temp <- df[[2]]; cycles <- df[[3]]

      # Capacity retention (larger-the-better)
      capacity_retention <- 100 - 0.001 * cycles - 0.00001 * cycles^2 -
                            0.5 * (temp - 25)^2 - 0.2 * (crate - 1)^2

      capacity_retention
    }
  )
)
