# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate c4' Constant via Monte Carlo Simulation
#' @name get_c4_prime_cpp
#' @description
#' Bias correction factor for MSSD (Mean Squared Successive Difference)
#' based sigma estimation. Returns the expected value of
#' \eqn{\sqrt{\sum (x_i - x_{i-1})^2 / (2(n-1))}} for standard normal
#' samples, used to unbias `sigma_estimate(method = "mssd")`.
#'
#' @param n Sample size (integer, >= 2).
#' @param B Number of Monte Carlo iterations (default 1,000,000).
#' @return Numeric scalar (double) — the c4' bias correction factor.
#'   Returns `NA_real_` for `n < 2`, and `sqrt(2/pi)` for `n = 2`.
#' @export
#' @examples
#' # c4' for small samples (small B for speed in examples;
#' # increase B for production accuracy)
#' set.seed(123)
#' get_c4_prime_cpp(n = 5, B = 1000)
#' get_c4_prime_cpp(n = 10, B = 1000)
#'
#' # n = 2 has closed form sqrt(2/pi) — no simulation needed
#' get_c4_prime_cpp(n = 2)  # approx 0.7978846
#' sqrt(2 / pi)
get_c4_prime_cpp <- function(n, B = 1000000L) {
    .Call(`_iQualityR_stat_get_c4_prime_cpp`, n, B)
}

