# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate c4 prime Constant using Monte Carlo Simulation
#' @name get_c4_prime_cpp
NULL

get_c4_prime_cpp <- function(n, B = 1000000L) {
    .Call(`_iQualityR_stat_get_c4_prime_cpp`, n, B)
}

